### PR TITLE
Fix DownloadCovidDataTotal - overwrite existing data

### LINKED ISSUE #105: v covidDataTotal se zobrazují neaktuální data
Na adrese https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/zakladni-prehled.json, kde získáváme JSON od ÚZIS proběhla aktualizace 6.10. v 18:00 (první přiložený screenshot z JSONu má datum aktualizace 18:11).

V collection [`covidDataTotal`](https://github.com/covid19cz/erouska-backend/wiki/database), kterou jsem otevřel ve 20:00 se ale pro 6.10. zobrazují neaktuální data (viz druhý screenshot).

Tento stav zdá se poukazuje na to, že funkce [`getCovidData`](https://github.com/covid19cz/erouska-backend/wiki/Firebase-Functions) se nespouští každou hodinu (což by měla).

image

image

### PR DESCRIPTION
**Pull request by jendakol**
Fixes #105 (code)

### CODE REVIEW

File: internal/functions/coviddata/download-covid-data-total.go [hunk 1]
```diff
@@ -137,9 +137,10 @@ func DownloadCovidDataTotal(w http.ResponseWriter, r *http.Request) {
 				return fmt.Errorf("Error while querying Firestore: %v", err)
 			}
 
-			return tx.Set(doc, *d)
+			return tx.Set(doc, *totalsData)
 		}
-		return nil
+
+		return tx.Set(doc, *totalsData)
```
Comment (marekaf) [inline internal/functions/coviddata/download-covid-data-total.go]: are you sure this will work? wouldn't the first return fmt.Errorf be returned first without ever reaching the tx.Set? Since the functionality is changing, I think it is reasonable to simplify this too and possibly get rid of the fmt.Errorf (maybe change it to Debugf("we didn't find a key and we are creating a new record") vs. Debugf("mutating data for this date"). wdyt?

Comment (jendakol) [reply internal/functions/coviddata/download-covid-data-total.go]: There are three cases:
1. The query fails because of error.
1. The query fails because the record doesn't exist yet.
1. The query succeeds.

`return fmt.Errorf` is only for the first case. In the second, data are just stored. In the third, the data can be thrown away and be overwritten.  
You are, however, right, that this can be simplified - the transaction is now not needed at all. Updated.

**Review by marekaf — APPROVED** [review]
lgtm
